name: Test Feature Branch

on:
  push:
    branches: [ "feature/*" ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Checkout project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Test with Maven
        run: mvn test --file pom.xml